repositories:
  - name: bitnami
    # url: https://charts.bitnami.com/bitnami
    # this mirro is used to avoid bocking from certain geographies
    # you can switch to the default one by uncommeniting the upper url and removing the mirror one
    url: https://mirror.yandex.ru/helm/charts.bitnami.com
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  local:
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

helmDefaults:
  timeout: 600

releases:
  - name: ingress-nginx
    labels:
      app: ingress-nginx
    wait: true
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - values-ingress-nginx.yaml.gotmpl

  - name: postgresql
    labels:
      app: postgresql
    wait: true
    chart: bitnami/postgresql
    version: 12.2.7
    values:
      - values-postgresql.yaml.gotmpl


  - name: minio-s3
    labels:
      app: minio-s3
    wait: true
    chart: bitnami/minio
    version: 14.8.5
    values: 
      - values-minio.yaml.gotmpl

  - name: rabbitmq
    labels:
      app: rabbitmq
    wait: true
    chart: bitnami/rabbitmq
    version: 16.0.3
    values:
      - values-rabbitmq.yaml.gotmpl


  - name: tourmanique-api
    labels:
      app: tourmanique-api
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
      - postgresql
      - minio-s3
    values:
    #   # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/tourmanique-api.git@/ci/values.yaml?ref={{ env "TOURMANIQUE_API_BRANCH" | default "develop" }}
      - values.yaml.gotmpl
      - values-tourmanique-api.yaml.gotmpl

  - name: tourmanique-color-service
    labels:
      app: tourmanique-color-service
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
      - postgresql
      - minio-s3
    values:
    #   # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/tourmanique-color-service.git@/ci/values.yaml?ref={{ env "TOURMANIQUE_COLOR_SERVICE_BRANCH" | default "develop" }}
      - values.yaml.gotmpl
      - values-tourmanique-color-service.yaml.gotmpl
